/**
 * @file    main.c
 * @brief   NUCLEO-G474RE + MPU-6050 — accel/gyro readout over UART
 *
 * Hardware connections (Arduino header / morpho):
 * ┌─────────────────┬──────────────────────────────────────────────┐
 * │ MPU-6050 pin    │ NUCLEO-G474RE pin                            │
 * ├─────────────────┼──────────────────────────────────────────────┤
 * │ VCC             │ 3.3 V  (CN6 pin 4)                           │
 * │ GND             │ GND    (CN6 pin 6)                           │
 * │ SCL             │ PB8  – Arduino D15 / CN5 pin 10  (I2C1_SCL) │
 * │ SDA             │ PB9  – Arduino D14 / CN5 pin 9   (I2C1_SDA) │
 * │ AD0             │ GND  → I2C address 0x68 (default)            │
 * │ INT             │ not connected (polling mode)                  │
 * └─────────────────┴──────────────────────────────────────────────┘
 *
 * UART output is routed through the ST-LINK Virtual COM Port (USART2,
 * PA2/PA3) at 115200 8N1 — open any serial terminal to see the data.
 *
 * CubeMX / CubeIDE peripheral settings required:
 *   • I2C1  : Standard Mode (100 kHz), PB8=SCL, PB9=SDA
 *   • USART2: Asynchronous, 115200 baud, 8N1 (ST-LINK VCP)
 *   • SYS   : Timebase source = SysTick
 *
 * Build: STM32CubeIDE with STM32CubeG4 HAL package.
 */

/* ------------------------------------------------------------------ */
/* Includes                                                             */
/* ------------------------------------------------------------------ */
#include "main.h"
#include "mpu6050.h"
#include <stdio.h>
#include <string.h>

/* ------------------------------------------------------------------ */
/* Private peripheral handles (generated by CubeMX / filled manually)  */
/* ------------------------------------------------------------------ */
I2C_HandleTypeDef  hi2c1;
UART_HandleTypeDef huart2;

/* ------------------------------------------------------------------ */
/* Private function prototypes                                          */
/* ------------------------------------------------------------------ */
static void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_I2C1_Init(void);
static void MX_USART2_UART_Init(void);

/* Redirect printf to USART2 */
static void uart_print(const char *str);

/* ------------------------------------------------------------------ */
/* main                                                                 */
/* ------------------------------------------------------------------ */
int main(void)
{
    /* HAL init, clock config, peripheral init */
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_USART2_UART_Init();
    MX_I2C1_Init();

    uart_print("\r\n=== NUCLEO-G474RE + MPU-6050 ===\r\n");

    /* Initialise MPU-6050 (AD0 = GND → address 0x68) */
    MPU6050_Status_t status = MPU6050_Init(&hi2c1, MPU6050_I2C_ADDR_LOW);
    if (status == MPU6050_WRONG_ID)
    {
        uart_print("[ERROR] WHO_AM_I mismatch — check wiring and AD0 pin.\r\n");
        Error_Handler();
    }
    else if (status != MPU6050_OK)
    {
        uart_print("[ERROR] I2C communication failed — check pull-ups and connections.\r\n");
        Error_Handler();
    }

    uart_print("[OK] MPU-6050 initialised.\r\n\r\n");
    uart_print("Accel[g]              Gyro[deg/s]           Temp[C]\r\n");
    uart_print("Ax       Ay       Az  Gx       Gy       Gz\r\n");
    uart_print("-------- -------- --- -------- -------- --------\r\n");

    MPU6050_Data_t data;
    char line[128];

    while (1)
    {
        if (MPU6050_ReadAll(&hi2c1, MPU6050_I2C_ADDR_LOW, &data) == MPU6050_OK)
        {
            /* Format: fixed-width columns, 3 decimal places */
            snprintf(line, sizeof(line),
                     "%+7.3f  %+7.3f  %+7.3f  "
                     "%+8.2f  %+8.2f  %+8.2f  "
                     "%6.2f\r\n",
                     data.accel_x, data.accel_y, data.accel_z,
                     data.gyro_x,  data.gyro_y,  data.gyro_z,
                     data.temp_c);
            uart_print(line);
        }
        else
        {
            uart_print("[WARN] Read failed — retrying...\r\n");
        }

        HAL_Delay(100); /* 10 Hz print rate */
    }
}

/* ------------------------------------------------------------------ */
/* UART helper                                                          */
/* ------------------------------------------------------------------ */
static void uart_print(const char *str)
{
    HAL_UART_Transmit(&huart2, (const uint8_t *)str, (uint16_t)strlen(str),
                      HAL_MAX_DELAY);
}

/* ------------------------------------------------------------------ */
/* Peripheral initialisations                                           */
/* ------------------------------------------------------------------ */

/**
 * @brief  System clock configuration for NUCLEO-G474RE.
 *         Uses the 24 MHz HSE on-board, PLL → 170 MHz SYSCLK.
 *         Matches the default CubeMX output for this board.
 */
static void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    /** Configure the main internal regulator output voltage */
    HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1_BOOST);

    /** Initialise the RCC Oscillators */
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    RCC_OscInitStruct.HSEState       = RCC_HSE_ON;
    RCC_OscInitStruct.PLL.PLLState   = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource  = RCC_PLLSOURCE_HSE;
    /* 24 MHz HSE × (85/2) / 6 = 170 MHz */
    RCC_OscInitStruct.PLL.PLLM = RCC_PLLM_DIV6;
    RCC_OscInitStruct.PLL.PLLN = 85;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
    RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
    RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
        Error_Handler();

    /** Initialise the CPU, AHB and APB buses clocks */
    RCC_ClkInitStruct.ClockType      = RCC_CLOCKTYPE_HCLK  | RCC_CLOCKTYPE_SYSCLK
                                     | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider  = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
    /* Flash latency 4 required at 170 MHz / Vcore boost */
    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4) != HAL_OK)
        Error_Handler();
}

/**
 * @brief  I2C1 initialisation — Standard Mode 100 kHz, PB8/PB9.
 */
static void MX_I2C1_Init(void)
{
    hi2c1.Instance              = I2C1;
    hi2c1.Init.Timing           = 0x30A0A7FB; /* 100 kHz @ 170 MHz PCLK1 */
    hi2c1.Init.OwnAddress1      = 0;
    hi2c1.Init.AddressingMode   = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.DualAddressMode  = I2C_DUALADDRESS_DISABLE;
    hi2c1.Init.OwnAddress2      = 0;
    hi2c1.Init.OwnAddress2Masks = I2C_OA2_NOMASK;
    hi2c1.Init.GeneralCallMode  = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode    = I2C_NOSTRETCH_DISABLE;
    if (HAL_I2C_Init(&hi2c1) != HAL_OK)
        Error_Handler();

    /* Enable analog and digital filters for noise immunity */
    if (HAL_I2CEx_ConfigAnalogFilter(&hi2c1, I2C_ANALOGFILTER_ENABLE) != HAL_OK)
        Error_Handler();
    if (HAL_I2CEx_ConfigDigitalFilter(&hi2c1, 0) != HAL_OK)
        Error_Handler();
}

/**
 * @brief  USART2 initialisation — 115200 8N1 (ST-LINK VCP, PA2/PA3).
 */
static void MX_USART2_UART_Init(void)
{
    huart2.Instance          = USART2;
    huart2.Init.BaudRate     = 115200;
    huart2.Init.WordLength   = UART_WORDLENGTH_8B;
    huart2.Init.StopBits     = UART_STOPBITS_1;
    huart2.Init.Parity       = UART_PARITY_NONE;
    huart2.Init.Mode         = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING_16;
    huart2.Init.OneBitSampling        = UART_ONE_BIT_SAMPLE_DISABLE;
    huart2.Init.ClockPrescaler        = UART_PRESCALER_DIV1;
    huart2.AdvancedInit.AdvFeatureInit = UART_ADVFEATURE_NO_INIT;
    if (HAL_UART_Init(&huart2) != HAL_OK)
        Error_Handler();
}

/**
 * @brief  GPIO initialisation.
 *         The HAL MSP callbacks (HAL_I2C_MspInit, HAL_UART_MspInit) handle
 *         the actual pin alternate-function configuration; this function
 *         enables the user LED (PA5) for optional status indication.
 */
static void MX_GPIO_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    __HAL_RCC_GPIOA_CLK_ENABLE();

    /* User LED LD2 on PA5 */
    GPIO_InitStruct.Pin   = GPIO_PIN_5;
    GPIO_InitStruct.Mode  = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull  = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_RESET);
}

/* ------------------------------------------------------------------ */
/* MSP callbacks — pin / clock setup called by HAL_xxx_Init()          */
/* ------------------------------------------------------------------ */

/**
 * @brief  I2C1 MSP Init — enables clocks and configures PB8/PB9 as
 *         open-drain alternate function (AF4 = I2C1 on STM32G4).
 */
void HAL_I2C_MspInit(I2C_HandleTypeDef *hi2c)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    if (hi2c->Instance == I2C1)
    {
        __HAL_RCC_GPIOB_CLK_ENABLE();
        __HAL_RCC_I2C1_CLK_ENABLE();

        /* PB8 = I2C1_SCL, PB9 = I2C1_SDA (AF4 on STM32G474) */
        GPIO_InitStruct.Pin       = GPIO_PIN_8 | GPIO_PIN_9;
        GPIO_InitStruct.Mode      = GPIO_MODE_AF_OD;   /* open-drain required for I2C */
        GPIO_InitStruct.Pull      = GPIO_NOPULL;       /* external pull-ups on breakout */
        GPIO_InitStruct.Speed     = GPIO_SPEED_FREQ_HIGH;
        GPIO_InitStruct.Alternate = GPIO_AF4_I2C1;
        HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
    }
}

/**
 * @brief  I2C1 MSP DeInit.
 */
void HAL_I2C_MspDeInit(I2C_HandleTypeDef *hi2c)
{
    if (hi2c->Instance == I2C1)
    {
        __HAL_RCC_I2C1_FORCE_RESET();
        __HAL_RCC_I2C1_RELEASE_RESET();
        HAL_GPIO_DeInit(GPIOB, GPIO_PIN_8 | GPIO_PIN_9);
    }
}

/**
 * @brief  USART2 MSP Init — PA2 (TX) / PA3 (RX), AF7.
 */
void HAL_UART_MspInit(UART_HandleTypeDef *huart)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    if (huart->Instance == USART2)
    {
        __HAL_RCC_GPIOA_CLK_ENABLE();
        __HAL_RCC_USART2_CLK_ENABLE();

        /* PA2 = USART2_TX, PA3 = USART2_RX (AF7 on STM32G474) */
        GPIO_InitStruct.Pin       = GPIO_PIN_2 | GPIO_PIN_3;
        GPIO_InitStruct.Mode      = GPIO_MODE_AF_PP;
        GPIO_InitStruct.Pull      = GPIO_NOPULL;
        GPIO_InitStruct.Speed     = GPIO_SPEED_FREQ_LOW;
        GPIO_InitStruct.Alternate = GPIO_AF7_USART2;
        HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
    }
}

/**
 * @brief  USART2 MSP DeInit.
 */
void HAL_UART_MspDeInit(UART_HandleTypeDef *huart)
{
    if (huart->Instance == USART2)
    {
        __HAL_RCC_USART2_FORCE_RESET();
        __HAL_RCC_USART2_RELEASE_RESET();
        HAL_GPIO_DeInit(GPIOA, GPIO_PIN_2 | GPIO_PIN_3);
    }
}

/* ------------------------------------------------------------------ */
/* Error handler                                                        */
/* ------------------------------------------------------------------ */
void Error_Handler(void)
{
    __disable_irq();
    /* Blink LD2 rapidly to signal a fault */
    while (1)
    {
        HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);
        for (volatile uint32_t i = 0; i < 500000UL; i++);
    }
}

#ifdef USE_FULL_ASSERT
void assert_failed(uint8_t *file, uint32_t line)
{
    (void)file; (void)line;
}
#endif
